spring.application.name=MultiDBApp

db1.datasource.jdbc-url=jdbc:mysql://localhost:3306/alien
db1.datasource.username=#######
db1.datasource.password=######


db2.datasource.jdbc-url=jdbc:postgresql://localhost:5432/multidb
db2.datasource.username=#######
db2.datasource.password=######

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8484
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true